#!/usr/bin/env bash

set -ex
set -eo pipefail

xcodebuild test \
-project "SQLite.xcodeproj" \
-scheme "SQLite iOS" \
-sdk iphonesimulator \
-destination "platform=iOS Simulator,name=iPhone X,OS=12.0" \
 | xcpretty -c
