name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@master

    - name: Install xcpretty
      run: gem install xcpretty

    - name: Use Xcode 12
      run: sudo xcode-select -s /Applications/Xcode_12.app
      
    - name: Test Swift Package
      run: swift test 2>&1 | xcpretty
